<?php
class Aws {
    static public function getData() {
        $c = stream_context_create([
            'http' => [
                'timeout' => 1,
            ]
        ]);
        if (@file_get_contents("http://169.254.169.254/latest/meta-data", false, $c) === false) {
            return null;
        }
        $userData = @file_get_contents("http://169.254.169.254/latest/user-data", false, $c);
        if($userData === false) {
            $userData = '<none>';
        }
        $result = [
            'meta-data' => self::getAwsData("http://169.254.169.254/latest/meta-data"),
            'dynamic' => self::getAwsData("http://169.254.169.254/latest/dynamic"),
            'user-data' => $userData,
        ];
        return $result;
    }

    static private function getAwsData($url)
    {
        $c = stream_context_create([
            'http' => [
                'timeout' => 1,
            ]
        ]);
        $data = file_get_contents($url, false, $c);

        $result = [];
        foreach(explode("\n", $data) as $name) {
            $name = strstr($name, '=', true) == '' ? $name : strstr($name, '=', true) . '/';
            if(strstr($name, '/')) {
                $result[$name] = self::getAwsData("{$url}/{$name}");
            } else if($name !== "") {
                $result[$name] = file_get_contents("{$url}/{$name}") ;
            }
        }
        return $result;
    }
}

$data = Aws::getData();
?>

<?php if (is_null($data)) : ?>
  <div style="padding: 10px;"><b>This plugin can be used only on AWS environment.</b></div>
  <div style="padding: 10px;"><b>Notice:</b> using this plugin on non-AWS server can significantly reduce Z-Ray performance.</div>
<?php else : ?>
<?php
$tableParams = [
    'tableId' => 'awsPanel',
    'tableWidth' => '4',
];
echo $this->zrayTable($tableParams);
?>

<script type="text/javascript">
(function() {
    var storage = zray.getStorage("invalidStorage");
    var data = <?=json_encode($data)?>;
    delete data.dynamic;
    storage.setData(data);
    var tree = zray.createTreeTable(storage, jQuery('#<?php echo $tableParams['tableId']; ?>'));
})();
</script>
<?php endif; ?>
